#ifndef _YGL_LIMITS_H_
#define _YGL_LIMITS_H_

#define MAX_VERTEX_BUF 100000
#define MAX_COMMAND_BUF 100000
#define GPU_MAX_VERTEX_BUF 200000
#define MAX_TEXOBJ_CNT 1000
#define MAX_TEXTURE_LEVEL 32

#define MAX_FRAMEBUF_SIZE 5000000
#define MAX_EDGETABLE_SIZE 2000
#define MAX_HSLS_CNT 4000

#define GL_MAX_LIGHTS 8
#define GL_MAX_MODELVIEW_STACK_DEPTH 32
#define GL_MAX_PROJECTION_STACK_DEPTH 2
#define GL_MAX_MAX_TEXTURE_STACK_DEPTH 2
#define GL_MAX_TEXTURE_SIZE 64
#define GL_MAX_NAME_STACK_DEPTH 64

#endif