#ifndef _YGL_CONSTANTS_
#define _YGL_CONSTANTS_


#define YGL_MAX_BUFFER_WIDTH 1024
#define YGL_MAX_BUFFER_HEIGHT 1024
#define YGL_MODELVIEW_STACK_DEPTH 32
#define YGL_PROJECTION_STACK_DEPTH 2
#define YGL_MAX_LIGHTS 8

// 2048?
#define YGL_TEXTURE_BASE_LEVEL 0
#define YGL_TEXTURE_MAX_LEVEL 11

#define YGL_TEXTURE_NAMES_MAX 128

#define YGL_DEPTH_BUFFER_BIT_DEPTH 32
#define YGL_DEPTH_BUFFER_MAX_RES ((unsigned int)0xffffffff)

// at most 64??
enum YGL_ENABLE_FLAGS{
	YGL_ALPHA_TEST,
	YGL_AUTO_NORMAL,
	YGL_BLEND,
	// YGL_CLIP_PLANEi,
	YGL_COLOR_LOGIC_OP,
	YGL_COLOR_MATERIAL,
	YGL_CULL_FACE,
	YGL_DEPTH_TEST,
	// YGL_DITHER, no support
	YGL_FOG,
	// YGL_INDEX_LOGIC_OP, no support
	// YGL_LIGHTi, // seperate
	YGL_LIGHTING,
	YGL_LINE_SMOOTH,
	YGL_LINE_STIPPLE,
	YGL_LOGIC_OP,
	YGL_MAP1_COLOR_4,
	YGL_MAP1_INDEX,
	YGL_MAP1_NORMAL,
	YGL_MAP1_TEXTURE_COORD_1,
	YGL_MAP1_TEXTURE_COORD_2,
	YGL_MAP1_TEXTURE_COORD_3,
	YGL_MAP1_TEXTURE_COORD_4,
	YGL_MAP1_VERTEX_3,
	YGL_MAP1_VERTEX_4,
	YGL_MAP2_COLOR_4,
	YGL_MAP2_INDEX,
	YGL_MAP2_NORMAL,
	YGL_MAP2_TEXTURE_COORD_1,
	YGL_MAP2_TEXTURE_COORD_2,
	YGL_MAP2_TEXTURE_COORD_3,
	YGL_MAP2_TEXTURE_COORD_4,
	YGL_MAP2_VERTEX_3,
	YGL_MAP2_VERTEX_4,
	YGL_NORMALIZE,
	YGL_POINT_SMOOTH,
	YGL_POLYGON_OFFSET_FILL,
	YGL_POLYGON_OFFSET_LINE,
	YGL_POLYGON_OFFSET_POINT,
	YGL_POLYGON_SMOOTH,
	YGL_POLYGON_STIPPLE,
	YGL_SCISSOR_TEST,
	YGL_STENCIL_TEST,
	YGL_TEXTURE_1D,
	YGL_TEXTURE_2D,
	YGL_TEXTURE_GEN_Q,
	YGL_TEXTURE_GEN_R,
	YGL_TEXTURE_GEN_S,
	YGL_TEXTURE_GEN_T ,
};

enum YGL_TEX_TARGET{
	YGL_TEX_TARGET_1D,
	YGL_TEX_TARGET_2D,
	YGL_TEX_TARGET_MAX,
};

enum YGL_TEX_COORDS{
	YGL_S,
	YGL_T,
	YGL_R,
	YGL_Q,
};

enum YGL_MODE_FLAGS{
	YGL_FLAT=0,
	YGL_SMOOTH=1,
	YGL_CCW=0,
	YGL_CW=1,
	YGL_BACK=1,
	YGL_FRONT=2,
	YGL_FRONT_AND_BACK=3, // 11b
};

enum YGL_WRITE_BUFFER{
	YGL_DEPTH_WRITE,
	YGL_R_WRITE,
	YGL_G_WRITE,
	YGL_B_WRITE,
	YGL_A_WRITE,
};

enum YGL_CLIENT_ARRAY
{
	YGL_COLOR_ARRAY,
	YGL_EDGE_FLAG_ARRAY,
	//YGL_INDEX_ARRAY,
	YGL_NORMAL_ARRAY,
	YGL_TEXTURE_COORD_ARRAY,
	YGL_VERTEX_ARRAY,

	YGL_CLIENT_ARRAY_MAX,
};



#endif