#ifndef _YGL_CONSTANTS_
#define _YGL_CONSTANTS_


#define YGL_MAX_BUFFER_WIDTH 512
#define YGL_MAX_BUFFER_HEIGHT 512
#define YGL_MODELVIEW_STACK_DEPTH 32
#define YGL_PROJECTION_STACK_DEPTH 2
#define YGL_MAX_LIGHTS 8

enum YGL_ENABLE_FLAGS{
	YGL_ALPHA_TEST,
	YGL_AUTO_NORMAL,
	YGL_BLEND,
	//YGL_CLIP_PLANEi,
	YGL_COLOR_LOGIC_OP,
	YGL_COLOR_MATERIAL,
	YGL_CULL_FACE,
	YGL_DEPTH_TEST,
	YGL_DITHER,
	YGL_FOG,
	YGL_INDEX_LOGIC_OP,
	//YGL_LIGHTi,
	YGL_LIGHTING,
	YGL_LINE_SMOOTH,
	YGL_LINE_STIPPLE,
	YGL_LOGIC_OP,
	YGL_MAP1_COLOR_4,
	YGL_MAP1_INDEX,
	YGL_MAP1_NORMAL,
	YGL_MAP1_TEXTURE_COORD_1,
	YGL_MAP1_TEXTURE_COORD_2,
	YGL_MAP1_TEXTURE_COORD_3,
	YGL_MAP1_TEXTURE_COORD_4,
	YGL_MAP1_VERTEX_3,
	YGL_MAP1_VERTEX_4,
	YGL_MAP2_COLOR_4,
	YGL_MAP2_INDEX,
	YGL_MAP2_NORMAL,
	YGL_MAP2_TEXTURE_COORD_1,
	YGL_MAP2_TEXTURE_COORD_2,
	YGL_MAP2_TEXTURE_COORD_3,
	YGL_MAP2_TEXTURE_COORD_4,
	YGL_MAP2_VERTEX_3,
	YGL_MAP2_VERTEX_4,
	YGL_NORMALIZE,
	YGL_POINT_SMOOTH,
	YGL_POLYGON_OFFSET_FILL,
	YGL_POLYGON_OFFSET_LINE,
	YGL_POLYGON_OFFSET_POINT,
	YGL_POLYGON_SMOOTH,
	YGL_POLYGON_STIPPLE,
	YGL_SCISSOR_TEST,
	YGL_STENCIL_TEST,
	YGL_TEXTURE_1D,
	YGL_TEXTURE_2D,
	YGL_TEXTURE_GEN_Q,
	YGL_TEXTURE_GEN_R,
	YGL_TEXTURE_GEN_S,
	YGL_TEXTURE_GEN_T ,
};

#endif